use_frameworks!

platform :ios, '9.0'

target 'LEGOPhotosManager_Example' do
  pod 'LEGOPhotosManager', :path => '../'
  pod 'Masonry'
  target 'LEGOPhotosManager_Tests' do
    inherit! :search_paths

    
  end
end
